### ISSUE TITLE
make check fails with a segfault since 1.16.4

### ISSUE THREAD

**Issue by heirecka** [spglib/spglib#157]
spglibtest segfaults with 1.16.4 while it worked fine with 1.16. Output of the test and a backtrace below:

```
test 1
    Start 1: spglibtest

1: Test command: /home/heiko/Quelltexte/git-sources/miscellaneous/spglib/build/spglibtest
1: Test timeout computed to be: 10000000
1: *** spg_find_primitive (BCC unitcell --> primitive) ***:
1: Lattice parameter:
1: -2.000000 2.000000 2.000000
1: 2.000000 -2.000000 2.000000
1: 2.000000 2.000000 -2.000000
1: Atomic positions:
1: 1: 0.000000 0.000000 0.000000
1: *** spg_find_primitive (Corundum) ***:
1: Lattice parameter:
1: 2.403817 1.387845 4.372423
1: -2.403817 1.387845 4.372423
1: 0.000000 -2.775689 4.372423
1: Atomic positions:
1: 1: 0.352185 0.352185 0.352185
1: 1: 0.647815 0.647815 0.647815
1: 1: 0.147815 0.147815 0.147815
1: 1: 0.852185 0.852185 0.852185
1: 2: 0.556167 0.943833 0.250000
1: 2: 0.443833 0.056167 0.750000
1: 2: 0.250000 0.556167 0.943833
1: 2: 0.750000 0.443833 0.056167
1: 2: 0.943833 0.250000 0.556167
1: 2: 0.056167 0.750000 0.443833
1: *** spg_standardize_cell (BCC unitcell --> primitive) ***:
1: ------------------------------------------------------
1: VASP POSCAR format: to_primitive=0 and no_idealize=0
1: 1.0
1: 4.000000 0.000000 0.000000
1: 0.000000 4.000000 0.000000
1: 0.000000 0.000000 4.000000
1: 2
1: Direct
1: 0.000000 0.000000 0.000000
1: 0.500000 0.500000 0.500000
1: ------------------------------------------------------
1: VASP POSCAR format: to_primitive=0 and no_idealize=1
1: 1.0
1: 3.970000 0.000000 0.000000
1: 0.000000 4.030000 0.000000
1: 0.000000 0.000000 4.000000
1: 2
1: Direct
1: 0.001000 0.000050 0.000000
1: 0.501000 0.500050 0.500000
1: ------------------------------------------------------
1: VASP POSCAR format: to_primitive=1 and no_idealize=0
1: 1.0
1: -2.000000 2.000000 2.000000
1: 2.000000 -2.000000 2.000000
1: 2.000000 2.000000 -2.000000
1: 1
1: Direct
1: 0.000000 0.000000 0.000000
1: ------------------------------------------------------
1: VASP POSCAR format: to_primitive=1 and no_idealize=1
1: 1.0
1: -1.985000 2.015000 2.000000
1: 1.985000 -2.015000 2.000000
1: 1.985000 2.015000 -2.000000
1: 1
1: Direct
1: 0.000050 0.001000 0.001050
1: ------------------------------------------------------
1: *** spg_standardize_cell (Corundum) ***:
1: ------------------------------------------------------
1: VASP POSCAR format: to_primitive=0 and no_idealize=0
1: 1.0
1: 4.807634 0.000000 0.000000
1: -2.403817 4.163534 0.000000
1: 0.000000 0.000000 13.117270
1: 30
1: Direct
1: 0.333333 0.666667 0.018852
1: 0.333333 0.666667 0.314482
1: 0.000000 0.000000 0.147815
1: 0.666667 0.333333 0.185518
1: 0.306167 0.000000 0.250000
1: 0.360499 0.333333 0.083333
1: 0.000000 0.306167 0.250000
1: 0.666667 0.027166 0.083333
1: 0.693833 0.693833 0.250000
1: 0.972834 0.639501 0.083333
1: 0.000000 0.000000 0.352185
1: 0.000000 0.000000 0.647815
1: 0.666667 0.333333 0.481148
1: 0.333333 0.666667 0.518852
1: 0.972834 0.333333 0.583333
1: 0.027166 0.666667 0.416667
1: 0.666667 0.639501 0.583333
1: 0.333333 0.360499 0.416667
1: 0.360499 0.027166 0.583333
1: 0.639501 0.972834 0.416667
1: 0.666667 0.333333 0.685518
1: 0.666667 0.333333 0.981148
1: 0.333333 0.666667 0.814482
1: 0.000000 0.000000 0.852185
1: 0.639501 0.666667 0.916667
1: 0.693833 0.000000 0.750000
1: 0.333333 0.972834 0.916667
1: 0.000000 0.693833 0.750000
1: 0.027166 0.360499 0.916667
1: 0.306167 0.306167 0.750000
1: ------------------------------------------------------
1: VASP POSCAR format: to_primitive=0 and no_idealize=1
1: 1.0
1: 4.807634 0.000000 -0.000000
1: -2.403817 4.163534 0.000000
1: -0.000000 0.000000 13.117270
1: 30
1: Direct
1: -0.000000 -0.000000 0.352185
1: 0.000000 0.000000 0.647815
1: 0.000000 0.000000 0.147815
1: -0.000000 -0.000000 0.852185
1: 0.972834 0.333333 0.583333
1: 0.027166 0.666667 0.416667
1: 0.666667 0.639501 0.583333
1: 0.333333 0.360499 0.416667
1: 0.360499 0.027166 0.583333
1: 0.639501 0.972834 0.416667
1: 0.666667 0.333333 0.685518
1: 0.666667 0.333333 0.981148
1: 0.666667 0.333333 0.481148
1: 0.666667 0.333333 0.185518
1: 0.639501 0.666667 0.916667
1: 0.693833 0.000000 0.750000
1: 0.333333 0.972834 0.916667
1: 0.000000 0.693833 0.750000
1: 0.027166 0.360499 0.916667
1: 0.306167 0.306167 0.750000
1: 0.333333 0.666667 0.018852
1: 0.333333 0.666667 0.314482
1: 0.333333 0.666667 0.814482
1: 0.333333 0.666667 0.518852
1: 0.306167 -0.000000 0.250000
1: 0.360499 0.333333 0.083333
1: 0.000000 0.306167 0.250000
1: 0.666667 0.027166 0.083333
1: 0.693833 0.693833 0.250000
1: 0.972834 0.639501 0.083333
1: ------------------------------------------------------
1: VASP POSCAR format: to_primitive=1 and no_idealize=0
1: 1.0
1: 2.403817 1.387845 4.372423
1: -2.403817 1.387845 4.372423
1: 0.000000 -2.775689 4.372423
1: 10
1: Direct
1: 0.352185 0.352185 0.352185
1: 0.647815 0.647815 0.647815
1: 0.147815 0.147815 0.147815
1: 0.852185 0.852185 0.852185
1: 0.556167 0.943833 0.250000
1: 0.443833 0.056167 0.750000
1: 0.250000 0.556167 0.943833
1: 0.750000 0.443833 0.056167
1: 0.943833 0.250000 0.556167
1: 0.056167 0.750000 0.443833
1: ------------------------------------------------------
1: VASP POSCAR format: to_primitive=1 and no_idealize=1
1: 1.0
1: 2.403817 1.387845 4.372423
1: -2.403817 1.387845 4.372423
1: -0.000000 -2.775689 4.372423
1: 10
1: Direct
1: 0.352185 0.352185 0.352185
1: 0.647815 0.647815 0.647815
1: 0.147815 0.147815 0.147815
1: 0.852185 0.852185 0.852185
1: 0.556167 0.943833 0.250000
1: 0.443833 0.056167 0.750000
1: 0.250000 0.556167 0.943833
1: 0.750000 0.443833 0.056167
1: 0.943833 0.250000 0.556167
1: 0.056167 0.750000 0.443833
1: ------------------------------------------------------
1/1 Test #1: spglibtest .......................***Exception: SegFault  0.11 sec
*** spg_find_primitive (BCC unitcell --> primitive) ***:
Lattice parameter:
-2.000000 2.000000 2.000000
2.000000 -2.000000 2.000000
2.000000 2.000000 -2.000000
Atomic positions:
1: 0.000000 0.000000 0.000000
*** spg_find_primitive (Corundum) ***:
Lattice parameter:
2.403817 1.387845 4.372423
-2.403817 1.387845 4.372423
0.000000 -2.775689 4.372423
Atomic positions:
1: 0.352185 0.352185 0.352185
1: 0.647815 0.647815 0.647815
1: 0.147815 0.147815 0.147815
1: 0.852185 0.852185 0.852185
2: 0.556167 0.943833 0.250000
2: 0.443833 0.056167 0.750000
2: 0.250000 0.556167 0.943833
2: 0.750000 0.443833 0.056167
2: 0.943833 0.250000 0.556167
2: 0.056167 0.750000 0.443833
*** spg_standardize_cell (BCC unitcell --> primitive) ***:
------------------------------------------------------
VASP POSCAR format: to_primitive=0 and no_idealize=0
1.0
4.000000 0.000000 0.000000
0.000000 4.000000 0.000000
0.000000 0.000000 4.000000
2
Direct
0.000000 0.000000 0.000000
0.500000 0.500000 0.500000
------------------------------------------------------
VASP POSCAR format: to_primitive=0 and no_idealize=1
1.0
3.970000 0.000000 0.000000
0.000000 4.030000 0.000000
0.000000 0.000000 4.000000
2
Direct
0.001000 0.000050 0.000000
0.501000 0.500050 0.500000
------------------------------------------------------
VASP POSCAR format: to_primitive=1 and no_idealize=0
1.0
-2.000000 2.000000 2.000000
2.000000 -2.000000 2.000000
2.000000 2.000000 -2.000000
1
Direct
0.000000 0.000000 0.000000
------------------------------------------------------
VASP POSCAR format: to_primitive=1 and no_idealize=1
1.0
-1.985000 2.015000 2.000000
1.985000 -2.015000 2.000000
1.985000 2.015000 -2.000000
1
Direct
0.000050 0.001000 0.001050
------------------------------------------------------
*** spg_standardize_cell (Corundum) ***:
------------------------------------------------------
VASP POSCAR format: to_primitive=0 and no_idealize=0
1.0
4.807634 0.000000 0.000000
-2.403817 4.163534 0.000000
0.000000 0.000000 13.117270
30
Direct
0.333333 0.666667 0.018852
0.333333 0.666667 0.314482
0.000000 0.000000 0.147815
0.666667 0.333333 0.185518
0.306167 0.000000 0.250000
0.360499 0.333333 0.083333
0.000000 0.306167 0.250000
0.666667 0.027166 0.083333
0.693833 0.693833 0.250000
0.972834 0.639501 0.083333
0.000000 0.000000 0.352185
0.000000 0.000000 0.647815
0.666667 0.333333 0.481148
0.333333 0.666667 0.518852
0.972834 0.333333 0.583333
0.027166 0.666667 0.416667
0.666667 0.639501 0.583333
0.333333 0.360499 0.416667
0.360499 0.027166 0.583333
0.639501 0.972834 0.416667
0.666667 0.333333 0.685518
0.666667 0.333333 0.981148
0.333333 0.666667 0.814482
0.000000 0.000000 0.852185
0.639501 0.666667 0.916667
0.693833 0.000000 0.750000
0.333333 0.972834 0.916667
0.000000 0.693833 0.750000
0.027166 0.360499 0.916667
0.306167 0.306167 0.750000
------------------------------------------------------
VASP POSCAR format: to_primitive=0 and no_idealize=1
1.0
4.807634 0.000000 -0.000000
-2.403817 4.163534 0.000000
-0.000000 0.000000 13.117270
30
Direct
-0.000000 -0.000000 0.352185
0.000000 0.000000 0.647815
0.000000 0.000000 0.147815
-0.000000 -0.000000 0.852185
0.972834 0.333333 0.583333
0.027166 0.666667 0.416667
0.666667 0.639501 0.583333
0.333333 0.360499 0.416667
0.360499 0.027166 0.583333
0.639501 0.972834 0.416667
0.666667 0.333333 0.685518
0.666667 0.333333 0.981148
0.666667 0.333333 0.481148
0.666667 0.333333 0.185518
0.639501 0.666667 0.916667
0.693833 0.000000 0.750000
0.333333 0.972834 0.916667
0.000000 0.693833 0.750000
0.027166 0.360499 0.916667
0.306167 0.306167 0.750000
0.333333 0.666667 0.018852
0.333333 0.666667 0.314482
0.333333 0.666667 0.814482
0.333333 0.666667 0.518852
0.306167 -0.000000 0.250000
0.360499 0.333333 0.083333
0.000000 0.306167 0.250000
0.666667 0.027166 0.083333
0.693833 0.693833 0.250000
0.972834 0.639501 0.083333
------------------------------------------------------
VASP POSCAR format: to_primitive=1 and no_idealize=0
1.0
2.403817 1.387845 4.372423
-2.403817 1.387845 4.372423
0.000000 -2.775689 4.372423
10
Direct
0.352185 0.352185 0.352185
0.647815 0.647815 0.647815
0.147815 0.147815 0.147815
0.852185 0.852185 0.852185
0.556167 0.943833 0.250000
0.443833 0.056167 0.750000
0.250000 0.556167 0.943833
0.750000 0.443833 0.056167
0.943833 0.250000 0.556167
0.056167 0.750000 0.443833
------------------------------------------------------
VASP POSCAR format: to_primitive=1 and no_idealize=1
1.0
2.403817 1.387845 4.372423
-2.403817 1.387845 4.372423
-0.000000 -2.775689 4.372423
10
Direct
0.352185 0.352185 0.352185
0.647815 0.647815 0.647815
0.147815 0.147815 0.147815
0.852185 0.852185 0.852185
0.556167 0.943833 0.250000
0.443833 0.056167 0.750000
0.250000 0.556167 0.943833
0.750000 0.443833 0.056167
0.943833 0.250000 0.556167
0.056167 0.750000 0.443833
------------------------------------------------------


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.11 sec

The following tests FAILED:
          1 - spglibtest (SEGFAULT)
Errors while running CTest
```

Backtrace:
```
(gdb) bt
#0  0x000055555555bb60 in get_exteneded_basis (aperiodic_axis=-1, lattice=0x73ec4abcb000, basis=0x7fffffffd660)
    at /home/heiko/Quelltexte/git-sources/miscellaneous/spglib/src/delaunay.c:339
#1  delaunay_reduce (red_lattice=red_lattice@entry=0x7fffffffd7f0, lattice=0x73ec4abcb000, aperiodic_axis=aperiodic_axis@entry=-1, symprec=1.0000000000000001e-05)
    at /home/heiko/Quelltexte/git-sources/miscellaneous/spglib/src/delaunay.c:128
#2  0x000055555555c93a in del_delaunay_reduce (min_lattice=min_lattice@entry=0x7fffffffd7f0, lattice=<optimized out>, symprec=<optimized out>)
    at /home/heiko/Quelltexte/git-sources/miscellaneous/spglib/src/delaunay.c:80
#3  0x0000555555563d8d in get_cell_with_smallest_lattice (symprec=1.0000000000000001e-05, cell=0x73cb35616000)
    at /home/heiko/Quelltexte/git-sources/miscellaneous/spglib/src/primitive.c:306
#4  get_primitive (cell=cell@entry=0x73cb35616000, symprec=symprec@entry=1.0000000000000001e-05, angle_tolerance=angle_tolerance@entry=-1)
    at /home/heiko/Quelltexte/git-sources/miscellaneous/spglib/src/primitive.c:247
#5  0x0000555555563f45 in prm_get_primitive (cell=cell@entry=0x73cb35616000, symprec=symprec@entry=1.0000000000000001e-05, angle_tolerance=angle_tolerance@entry=-1)
    at /home/heiko/Quelltexte/git-sources/miscellaneous/spglib/src/primitive.c:141
#6  0x000055555555ca63 in get_spacegroup_and_primitive (angle_symprec=-1, symprec=1.0000000000000001e-05, hall_number=0, cell=0x73cb35616000)
    at /home/heiko/Quelltexte/git-sources/miscellaneous/spglib/src/determination.c:142
#7  det_determine_all (cell=cell@entry=0x73cb35616000, hall_number=hall_number@entry=0, symprec=symprec@entry=1.0000000000000001e-05, angle_symprec=angle_symprec@entry=-1)
    at /home/heiko/Quelltexte/git-sources/miscellaneous/spglib/src/determination.c:72
#8  0x000055555556b896 in get_dataset (lattice=0x7fffffffda20, lattice@entry=0x7fffffffd980, position=0x7fffffffd9f0, position@entry=0x7fffffffd950, types=0x7fffffffd9e8, 
    types@entry=0x7fffffffd948, num_atom=num_atom@entry=2, hall_number=hall_number@entry=0, symprec=symprec@entry=1.0000000000000001e-05, 
    angle_tolerance=angle_tolerance@entry=-1) at /home/heiko/Quelltexte/git-sources/miscellaneous/spglib/src/spglib.c:1265
#9  0x000055555556c852 in get_multiplicity (angle_tolerance=-1, symprec=symprec@entry=1.0000000000000001e-05, num_atom=num_atom@entry=2, types=types@entry=0x7fffffffd948, 
    position=position@entry=0x7fffffffd950, lattice=lattice@entry=0x7fffffffd980) at /home/heiko/Quelltexte/git-sources/miscellaneous/spglib/src/spglib.c:1804
#10 spg_get_multiplicity (lattice=lattice@entry=0x7fffffffda20, position=position@entry=0x7fffffffd9f0, types=types@entry=0x7fffffffd9e8, num_atom=num_atom@entry=2, 
    symprec=symprec@entry=1.0000000000000001e-05) at /home/heiko/Quelltexte/git-sources/miscellaneous/spglib/src/spglib.c:655
#11 0x000055555555a110 in test_spg_get_multiplicity () at /home/heiko/Quelltexte/git-sources/miscellaneous/spglib/src/test.c:536
#12 0x00005555555582a6 in main () at /home/heiko/Quelltexte/git-sources/miscellaneous/spglib/src/test.c:75
```

**Comment by atztogo** [comment]
Thanks @heirecka for your very helpful report.

I fixed it (#158) and released v1.16.5, https://pypi.org/project/spglib/1.16.5/.

**Comment by atztogo** [comment]
I will close this issue because it was fixed.

**Comment by heirecka** [comment]
Right, thanks!
