### ISSUE TITLE
pip install doesn't work for macosx (arm64)

### ISSUE THREAD

**Issue by atztogo** [spglib/spglib#212]
It seems PR #210 results in failing `pip install` even without `-e`.

The error shows `wheel/macosx_libfile.py` complains. `wheel` package is invoked by skbuild. It seems this is difficult to fix (for me), but critical. Until this issue will be fixed someday, I think it is better a little bit to step back.

How about making static link library using cmake, then link it in `setup.py` without relying on skbuild?

Ping @LecrisUT.

**Comment by LecrisUT** [comment]
That is rather curious. Please send me more debug details on it. If it doesn't output a cmake issue, it shouldn't be related to scikit-build. If it is a runtime error, we can fix it with static library, but it seems it is in the build process.

The error is at `pip install .` not on ` python setup.py build` right?

**Comment by LecrisUT** [comment]
Is [this solution](https://github.com/scikit-build/scikit-build/issues/717#issuecomment-1194922841) related?

**Comment by atztogo** [comment]
> Is [this solution](https://github.com/scikit-build/scikit-build/issues/717#issuecomment-1194922841) related?

It seems not, but perhaps. 

Right, `pip install .`
The last part of the log is shown below,

```
...
 Install the project...
  -- Install configuration: "Release"
  -- Installing: /Users/togo/code/atztogo/spglib/python/_skbuild/macosx--arm64-3.10/cmake-install/lib/libsymspg.2.0.2.dylib
  -- Installing: /Users/togo/code/atztogo/spglib/python/_skbuild/macosx--arm64-3.10/cmake-install/lib/libsymspg.1.dylib
  -- Installing: /Users/togo/code/atztogo/spglib/python/_skbuild/macosx--arm64-3.10/cmake-install/lib/libsymspg.dylib
  -- Installing: /Users/togo/code/atztogo/spglib/python/_skbuild/macosx--arm64-3.10/cmake-install/lib/libsymspg.a
  -- Installing: /Users/togo/code/atztogo/spglib/python/_skbuild/macosx--arm64-3.10/cmake-install/include/spglib.h
  -- Installing: /Users/togo/code/atztogo/spglib/python/_skbuild/macosx--arm64-3.10/cmake-install/include/spglib_f08.f90
  -- Installing: /Users/togo/code/atztogo/spglib/python/_skbuild/macosx--arm64-3.10/cmake-install/python/_spglib.cpython-310-darwin.so
  [cctools-port]: generating fake signature for '/Users/togo/code/atztogo/spglib/python/_skbuild/macosx--arm64-3.10/cmake-install/python/_spglib.cpython-310-darwin.so'
  -- Installing: /Users/togo/code/atztogo/spglib/python/_skbuild/macosx--arm64-3.10/cmake-install/spglib/libsymspg.2.0.2.dylib
  -- Installing: /Users/togo/code/atztogo/spglib/python/_skbuild/macosx--arm64-3.10/cmake-install/spglib/libsymspg.1.dylib
  -- Installing: /Users/togo/code/atztogo/spglib/python/_skbuild/macosx--arm64-3.10/cmake-install/spglib/libsymspg.dylib
  -- Installing: /Users/togo/code/atztogo/spglib/python/_skbuild/macosx--arm64-3.10/cmake-install/spglib/_spglib.cpython-310-darwin.so
  [cctools-port]: generating fake signature for '/Users/togo/code/atztogo/spglib/python/_skbuild/macosx--arm64-3.10/cmake-install/spglib/_spglib.cpython-310-darwin.so'
  -- Installing: /Users/togo/code/atztogo/spglib/python/_skbuild/macosx--arm64-3.10/cmake-install/lib/pkgconfig/spglib.pc
  -- Installing: /Users/togo/code/atztogo/spglib/python/_skbuild/macosx--arm64-3.10/cmake-install/lib/cmake/spglib/spglibConfigVersion.cmake
  -- Installing: /Users/togo/code/atztogo/spglib/python/_skbuild/macosx--arm64-3.10/cmake-install/lib/cmake/spglib/spglibConfig.cmake
  -- Installing: /Users/togo/code/atztogo/spglib/python/_skbuild/macosx--arm64-3.10/cmake-install/lib/cmake/spglib/spglibTargets.cmake
  -- Installing: /Users/togo/code/atztogo/spglib/python/_skbuild/macosx--arm64-3.10/cmake-install/lib/cmake/spglib/spglibTargets-release.cmake

  copying spglib/__init__.py -> _skbuild/macosx--arm64-3.10/cmake-install/spglib/__init__.py
  copying spglib/spglib.py -> _skbuild/macosx--arm64-3.10/cmake-install/spglib/spglib.py

  running bdist_wheel
  running build
  running build_py
  creating _skbuild/macosx--arm64-3.10/setuptools/lib.macosx--arm64-cpython-310
  creating _skbuild/macosx--arm64-3.10/setuptools/lib.macosx--arm64-cpython-310/spglib
  copying _skbuild/macosx--arm64-3.10/cmake-install/spglib/__init__.py -> _skbuild/macosx--arm64-3.10/setuptools/lib.macosx--arm64-cpython-310/spglib
  copying _skbuild/macosx--arm64-3.10/cmake-install/spglib/spglib.py -> _skbuild/macosx--arm64-3.10/setuptools/lib.macosx--arm64-cpython-310/spglib
  copying _skbuild/macosx--arm64-3.10/cmake-install/spglib/libsymspg.2.0.2.dylib -> _skbuild/macosx--arm64-3.10/setuptools/lib.macosx--arm64-cpython-310/spglib
  copying _skbuild/macosx--arm64-3.10/cmake-install/spglib/libsymspg.1.dylib -> _skbuild/macosx--arm64-3.10/setuptools/lib.macosx--arm64-cpython-310/spglib
  copying _skbuild/macosx--arm64-3.10/cmake-install/spglib/libsymspg.dylib -> _skbuild/macosx--arm64-3.10/setuptools/lib.macosx--arm64-cpython-310/spglib
  copying _skbuild/macosx--arm64-3.10/cmake-install/spglib/_spglib.cpython-310-darwin.so -> _skbuild/macosx--arm64-3.10/setuptools/lib.macosx--arm64-cpython-310/spglib
  copied 2 files
  running build_ext
  installing to _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel
  running install
  running install_lib
  creating _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64
  creating _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel
  creating _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib
  copying _skbuild/macosx--arm64-3.10/setuptools/lib.macosx--arm64-cpython-310/spglib/__init__.py -> _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib
  copying _skbuild/macosx--arm64-3.10/setuptools/lib.macosx--arm64-cpython-310/spglib/libsymspg.1.dylib -> _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib
  copying _skbuild/macosx--arm64-3.10/setuptools/lib.macosx--arm64-cpython-310/spglib/libsymspg.dylib -> _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib
  copying _skbuild/macosx--arm64-3.10/setuptools/lib.macosx--arm64-cpython-310/spglib/libsymspg.2.0.2.dylib -> _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib
  copying _skbuild/macosx--arm64-3.10/setuptools/lib.macosx--arm64-cpython-310/spglib/_spglib.cpython-310-darwin.so -> _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib
  copying _skbuild/macosx--arm64-3.10/setuptools/lib.macosx--arm64-cpython-310/spglib/spglib.py -> _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib
  copied 6 files
  running install_data
  creating _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib-2.0.2.data
  creating _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib-2.0.2.data/data
  creating _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib-2.0.2.data/data/lib
  copying _skbuild/macosx--arm64-3.10/cmake-install/lib/libsymspg.a -> _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib-2.0.2.data/data/lib
  copying _skbuild/macosx--arm64-3.10/cmake-install/lib/libsymspg.2.0.2.dylib -> _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib-2.0.2.data/data/lib
  copying _skbuild/macosx--arm64-3.10/cmake-install/lib/libsymspg.dylib -> _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib-2.0.2.data/data/lib
  copying _skbuild/macosx--arm64-3.10/cmake-install/lib/libsymspg.1.dylib -> _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib-2.0.2.data/data/lib
  creating _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib-2.0.2.data/data/include
  copying _skbuild/macosx--arm64-3.10/cmake-install/include/spglib.h -> _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib-2.0.2.data/data/include
  copying _skbuild/macosx--arm64-3.10/cmake-install/include/spglib_f08.f90 -> _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib-2.0.2.data/data/include
  creating _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib-2.0.2.data/data/python
  copying _skbuild/macosx--arm64-3.10/cmake-install/python/_spglib.cpython-310-darwin.so -> _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib-2.0.2.data/data/python
  creating _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib-2.0.2.data/data/lib/pkgconfig
  copying _skbuild/macosx--arm64-3.10/cmake-install/lib/pkgconfig/spglib.pc -> _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib-2.0.2.data/data/lib/pkgconfig
  creating _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib-2.0.2.data/data/lib/cmake
  creating _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib-2.0.2.data/data/lib/cmake/spglib
  copying _skbuild/macosx--arm64-3.10/cmake-install/lib/cmake/spglib/spglibConfigVersion.cmake -> _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib-2.0.2.data/data/lib/cmake/spglib
  copying _skbuild/macosx--arm64-3.10/cmake-install/lib/cmake/spglib/spglibTargets.cmake -> _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib-2.0.2.data/data/lib/cmake/spglib
  copying _skbuild/macosx--arm64-3.10/cmake-install/lib/cmake/spglib/spglibConfig.cmake -> _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib-2.0.2.data/data/lib/cmake/spglib
  copying _skbuild/macosx--arm64-3.10/cmake-install/lib/cmake/spglib/spglibTargets-release.cmake -> _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib-2.0.2.data/data/lib/cmake/spglib
  running install_egg_info
  running egg_info
  writing spglib.egg-info/PKG-INFO
  writing dependency_links to spglib.egg-info/dependency_links.txt
  writing requirements to spglib.egg-info/requires.txt
  writing top-level names to spglib.egg-info/top_level.txt
  reading manifest file 'spglib.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'src/*.h'
  warning: no files found matching 'src/*.c'
  warning: no files found matching '__nanoversion__.txt'
  writing manifest file 'spglib.egg-info/SOURCES.txt'
  Copying spglib.egg-info to _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/spglib-2.0.2-py3.10.egg-info
  running install_scripts
  copied 0 files
  Traceback (most recent call last):
    File "/Users/togo/.miniforge/envs/dev/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
      main()
    File "/Users/togo/.miniforge/envs/dev/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/togo/.miniforge/envs/dev/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 249, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/private/var/folders/r2/0x6s4wjn65q78crt1zns1lcm0000gn/T/pip-build-env-afjs1e54/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 413, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/private/var/folders/r2/0x6s4wjn65q78crt1zns1lcm0000gn/T/pip-build-env-afjs1e54/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/r2/0x6s4wjn65q78crt1zns1lcm0000gn/T/pip-build-env-afjs1e54/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 44, in <module>
    File "/private/var/folders/r2/0x6s4wjn65q78crt1zns1lcm0000gn/T/pip-build-env-afjs1e54/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 745, in setup
      return setuptools.setup(**kw)
    File "/private/var/folders/r2/0x6s4wjn65q78crt1zns1lcm0000gn/T/pip-build-env-afjs1e54/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "/private/var/folders/r2/0x6s4wjn65q78crt1zns1lcm0000gn/T/pip-build-env-afjs1e54/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
    File "/private/var/folders/r2/0x6s4wjn65q78crt1zns1lcm0000gn/T/pip-build-env-afjs1e54/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/private/var/folders/r2/0x6s4wjn65q78crt1zns1lcm0000gn/T/pip-build-env-afjs1e54/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/private/var/folders/r2/0x6s4wjn65q78crt1zns1lcm0000gn/T/pip-build-env-afjs1e54/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
      super().run_command(command)
    File "/private/var/folders/r2/0x6s4wjn65q78crt1zns1lcm0000gn/T/pip-build-env-afjs1e54/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/private/var/folders/r2/0x6s4wjn65q78crt1zns1lcm0000gn/T/pip-build-env-afjs1e54/overlay/lib/python3.10/site-packages/skbuild/command/bdist_wheel.py", line 31, in run
      super().run(*args, **kwargs)
    File "/private/var/folders/r2/0x6s4wjn65q78crt1zns1lcm0000gn/T/pip-build-env-afjs1e54/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 362, in run
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/private/var/folders/r2/0x6s4wjn65q78crt1zns1lcm0000gn/T/pip-build-env-afjs1e54/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 280, in get_tag
      plat_name = get_platform(self.bdist_dir)
    File "/private/var/folders/r2/0x6s4wjn65q78crt1zns1lcm0000gn/T/pip-build-env-afjs1e54/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 51, in get_platform
      result = calculate_macosx_platform_tag(archive_root, result)
    File "/private/var/folders/r2/0x6s4wjn65q78crt1zns1lcm0000gn/T/pip-build-env-afjs1e54/overlay/lib/python3.10/site-packages/wheel/macosx_libfile.py", line 399, in calculate_macosx_platform_tag
      base_version = tuple(int(x) for x in base_version.split("."))
    File "/private/var/folders/r2/0x6s4wjn65q78crt1zns1lcm0000gn/T/pip-build-env-afjs1e54/overlay/lib/python3.10/site-packages/wheel/macosx_libfile.py", line 399, in <genexpr>
      base_version = tuple(int(x) for x in base_version.split("."))
  ValueError: invalid literal for int() with base 10: ''
  error: subprocess-exited-with-error

  × Building wheel for spglib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /Users/togo/.miniforge/envs/dev/bin/python3.10 /Users/togo/.miniforge/envs/dev/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/r2/0x6s4wjn65q78crt1zns1lcm0000gn/T/tmp742wwa6f
  cwd: /Users/togo/code/atztogo/spglib/python
  Building wheel for spglib (pyproject.toml) ... error
  ERROR: Failed building wheel for spglib
Failed to build spglib
ERROR: Could not build wheels for spglib, which is required to install pyproject.toml-based projects
Exception information:
Traceback (most recent call last):
  File "/Users/togo/.miniforge/envs/dev/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/Users/togo/.miniforge/envs/dev/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/Users/togo/.miniforge/envs/dev/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 464, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for spglib, which is required to install pyproject.toml-based projects
Remote version of pip: 22.3.1
Local version of pip:  22.3.1
Was pip installed by pip? False
Removed build tracker: '/private/var/folders/r2/0x6s4wjn65q78crt1zns1lcm0000gn/T/pip-build-tracker-ctnubvfp'
```

**Comment by LecrisUT** [comment]
Seems to be the same error as the one I've linked.
Can you edit [this line](https://github.com/spglib/spglib/blob/b8d068bb3246b167df69edee911376580f58fa5b/python/setup.py#L64) and add your version of macos via `-DCMAKE_OSX_DEPLOYMENT_TARGET=....`?

**Comment by atztogo** [comment]
OK, it worked!

**Comment by atztogo** [comment]
Note about my system:
```python
In [2]: import platform

In [3]: platform.system()
Out[3]: 'Darwin'

In [4]: platform.version()
Out[4]: 'Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000'

In [5]: platform.release()
Out[5]: '22.2.0'

In [6]: platform.mac_ver()
Out[6]: ('13.1', ('', '', ''), 'arm64')
```
