### ISSUE TITLE
spglib 2.1.0 fails on alpine/python3.11

### ISSUE THREAD

**Issue by tmcqueen-materials** [spglib/spglib#326]
We have a bunch of backend tooling built on running various pieces of python inside docker containers. With spglib 2.0.2, the command `pip install spglib` succeeds, and then use of spglib proceeds without issue.

However, as of spg 2.1.0 released yesterday, `pip install spglib` appears to succeed, but when attempting to use the package within python, it results in an error:
```
2023-09-11T20:21:37.802209516-04:00 stderr F     import spglib
2023-09-11T20:21:37.802219426-04:00 stderr F   File "/usr/local/lib/python3.11/site-packages/spglib/__init__.py", line 37, in <module>
2023-09-11T20:21:37.802277547-04:00 stderr F     from .spglib import (  # noqa: F401
2023-09-11T20:21:37.802290897-04:00 stderr F   File "/usr/local/lib/python3.11/site-packages/spglib/spglib.py", line 59, in <module>
2023-09-11T20:21:37.802341138-04:00 stderr F     from spglib import _spglib as spg
2023-09-11T20:21:37.802355758-04:00 stderr F ImportError: Error loading shared library libsymspg.so.2: No such file or directory (needed by /usr/local/lib/python3.11/site-packages/spglib/_spglib.cpython-311-x86_64-linux-musl.so)
```

I don't know what changed, but it would be great to restore compatibility with Alphine/python.

**Comment by LecrisUT** [comment]
By alpine, do you mean alpine linux? It seems that it is not packaged and tested properly. We'll have to discuss with the downstream packagers there.

Just as a sanity check, can you install it in a virtual environment and test that?

**Comment by LecrisUT** [comment]
I cannot find any spglib package in Alpine linux, so could you clarify the steps you did to install? What docker containers are you working with? And if you can find any packagers responsible for this?

Can you check what files are installed for spglib, in `/usr/local/lib/python3.11/site-packages/spglib/` and in other system lib directories? There should be a file `libsymspg.so.2`

**Comment by tmcqueen-materials** [comment]
@LecrisUT : Sure, no problem. As you inferred, spglib is not packaged by alpine linux. But it has been easy to use from within python running on apline linux containers by installing via `pip` (which automatically executes the appropriate build). A minimal reproducer consists of this `Dockerfile`:
```
FROM python:alpine

LABEL Build docker build --rm --tag test/spglib .
LABEL Run docker run --rm test/spglib
LABEL Some older EL hosts might require changing to python:alpine3.13

WORKDIR /usr/src/app

RUN apk update && \
    apk add binutils musl-dev gcc linux-headers gfortran build-base wget freetype-dev libpng-dev openblas-dev && \
    ln -s /usr/include/locale.h /usr/include/xlocale.h && \
    pip install --no-cache-dir spglib && \
    mkdir /usr/src/app/data && \
    apk del gcc

COPY test.py ./

WORKDIR /usr/src/app/data

CMD [ "../test.py" ]
```

And the associated `test.py` script:
```
#!/usr/local/bin/python
import spglib
print("SPGLIB import succeeded.")
```

When using spglib 2.0.2, the above succeeds:
```
# podman build --rm --tag test/spglib .
STEP 1/9: FROM python:alpine
STEP 2/9: LABEL Build docker build --rm --tag test/spglib .
--> Using cache 60b522cb920f2d64cdc2fc58c6dbf9ad9b72c9be63bf3c214a2235b624365d76
--> 60b522cb920
STEP 3/9: LABEL Run docker run --rm test/spglib
--> Using cache 6cb82f6bc348fdcad8a9585a889b7a1a678bbad54c1007a1971a231dbd3d9fbd
--> 6cb82f6bc34
STEP 4/9: LABEL Some older EL hosts might require changing to python:alpine3.13
--> Using cache ca34d5ae45cc5db531e01be156e0ff9ce7d0a0fde61fcf9315b647ae79344129
--> ca34d5ae45c
STEP 5/9: WORKDIR /usr/src/app
--> Using cache 013bdb981a2eb1ff4965d1a6000a67bf4b4d2e00426cf9bfa6d69e45f86c8a21
--> 013bdb981a2
STEP 6/9: RUN apk update &&     apk add binutils musl-dev gcc linux-headers gfortran build-base wget freetype-dev libpng-dev openblas-dev &&     ln -s /usr/include/locale.h /usr/include/xlocale.h &&     pip install --no-cache-dir spglib==2.0.2 &&     mkdir /usr/src/app/data &&     apk del gcc
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
v3.18.3-169-gd5adf7d7d28 [https://dl-cdn.alpinelinux.org/alpine/v3.18/main]
v3.18.3-174-gbf4e0cf02dc [https://dl-cdn.alpinelinux.org/alpine/v3.18/community]
OK: 20064 distinct packages available
(1/43) Installing libgcc (12.2.1_git20220924-r10)
(2/43) Installing libstdc++ (12.2.1_git20220924-r10)
(3/43) Installing zstd-libs (1.5.5-r4)
(4/43) Installing binutils (2.40-r7)
(5/43) Installing libmagic (5.45-r0)
(6/43) Installing file (5.45-r0)
(7/43) Installing libgomp (12.2.1_git20220924-r10)
(8/43) Installing libatomic (12.2.1_git20220924-r10)
(9/43) Installing gmp (6.2.1-r3)
(10/43) Installing isl26 (0.26-r1)
(11/43) Installing mpfr4 (4.2.0_p12-r0)
(12/43) Installing mpc1 (1.3.1-r1)
(13/43) Installing gcc (12.2.1_git20220924-r10)
(14/43) Installing libstdc++-dev (12.2.1_git20220924-r10)
(15/43) Installing musl-dev (1.2.4-r1)
(16/43) Installing libc-dev (0.7.2-r5)
(17/43) Installing g++ (12.2.1_git20220924-r10)
(18/43) Installing make (4.4.1-r1)
(19/43) Installing fortify-headers (1.1-r3)
(20/43) Installing patch (2.7.6-r10)
(21/43) Installing build-base (0.5-r3)
(22/43) Installing brotli-libs (1.0.9-r14)
(23/43) Installing libpng (1.6.39-r3)
(24/43) Installing freetype (2.13.0-r5)
(25/43) Installing brotli (1.0.9-r14)
(26/43) Installing pkgconf (1.9.5-r0)
(27/43) Installing brotli-dev (1.0.9-r14)
(28/43) Installing zlib-dev (1.2.13-r1)
(29/43) Installing libpng-dev (1.6.39-r3)
(30/43) Installing freetype-dev (2.13.0-r5)
(31/43) Installing libquadmath (12.2.1_git20220924-r10)
(32/43) Installing libgfortran (12.2.1_git20220924-r10)
(33/43) Installing gfortran (12.2.1_git20220924-r10)
(34/43) Installing linux-headers (6.3-r0)
(35/43) Installing openblas (0.3.23-r0)
(36/43) Installing liblapack (0.3.23-r0)
(37/43) Installing liblapacke (0.3.23-r0)
(38/43) Installing openblas-ilp64 (0.3.23-r0)
(39/43) Installing openblas-dev (0.3.23-r0)
(40/43) Installing libunistring (1.1-r1)
(41/43) Installing libidn2 (2.3.4-r1)
(42/43) Installing pcre2 (10.42-r1)
(43/43) Installing wget (1.21.4-r0)
Executing busybox-1.36.1-r2.trigger
OK: 378 MiB in 81 packages
Collecting spglib==2.0.2
  Downloading spglib-2.0.2.tar.gz (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 12.4 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting numpy (from spglib==2.0.2)
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/cd/fe/e900cb2ebafae04b7570081cefc65b6fdd9e202b9b353572506cea5cafdf/numpy-1.25.2-cp311-cp311-musllinux_1_1_x86_64.whl.metadata
  Downloading numpy-1.25.2-cp311-cp311-musllinux_1_1_x86_64.whl.metadata (5.6 kB)
Downloading numpy-1.25.2-cp311-cp311-musllinux_1_1_x86_64.whl (18.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.1/18.1 MB 107.5 MB/s eta 0:00:00
Building wheels for collected packages: spglib
  Building wheel for spglib (pyproject.toml): started
  Building wheel for spglib (pyproject.toml): finished with status 'done'
  Created wheel for spglib: filename=spglib-2.0.2-cp311-cp311-linux_x86_64.whl size=528220 sha256=2acb4cabbf92b0d0a5bad467a1b10f3be4bf74b1175461ed26d929795341b9d3
  Stored in directory: /tmp/pip-ephem-wheel-cache-m7xenqez/wheels/5e/35/15/22506c066e169c3a1aa69af77c56c4ef7b27c40c02b4ef7c30
Successfully built spglib
Installing collected packages: numpy, spglib
Successfully installed numpy-1.25.2 spglib-2.0.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
World updated, but the following packages are not removed due to:
  gcc: build-base gfortran openblas-dev

OK: 378 MiB in 81 packages
--> 35b3f27167a
STEP 7/9: COPY test.py ./
--> 627e6d103e5
STEP 8/9: WORKDIR /usr/src/app/data
--> 6b0615818c2
STEP 9/9: CMD [ "../test.py" ]
COMMIT test/spglib
--> 025a7da48e8
Successfully tagged localhost/test/spglib:latest
025a7da48e844601f5dbcd6a9b633a85605c6a1a3aaa603982f6b3d2322a28d1

# podman run --rm test/spglib
SPGLIB import succeeded
#
```

Whereas when using spglib 2.1.0, it fails at runtime with a cannot find shared library error:
```
# podman build --rm --tag test/spglib .
STEP 1/9: FROM python:alpine
STEP 2/9: LABEL Build docker build --rm --tag test/spglib .
--> 60b522cb920
STEP 3/9: LABEL Run docker run --rm test/spglib
--> 6cb82f6bc34
STEP 4/9: LABEL Some older EL hosts might require changing to python:alpine3.13
--> ca34d5ae45c
STEP 5/9: WORKDIR /usr/src/app
--> 013bdb981a2
STEP 6/9: RUN apk update &&     apk add binutils musl-dev gcc linux-headers gfortran build-base wget freetype-dev libpng-dev openblas-dev &&     ln -s /usr/include/locale.h /usr/include/xlocale.h &&     pip install --no-cache-dir spglib &&     mkdir /usr/src/app/data &&     apk del gcc
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
v3.18.3-169-gd5adf7d7d28 [https://dl-cdn.alpinelinux.org/alpine/v3.18/main]
v3.18.3-174-gbf4e0cf02dc [https://dl-cdn.alpinelinux.org/alpine/v3.18/community]
OK: 20064 distinct packages available
(1/43) Installing libgcc (12.2.1_git20220924-r10)
(2/43) Installing libstdc++ (12.2.1_git20220924-r10)
(3/43) Installing zstd-libs (1.5.5-r4)
(4/43) Installing binutils (2.40-r7)
(5/43) Installing libmagic (5.45-r0)
(6/43) Installing file (5.45-r0)
(7/43) Installing libgomp (12.2.1_git20220924-r10)
(8/43) Installing libatomic (12.2.1_git20220924-r10)
(9/43) Installing gmp (6.2.1-r3)
(10/43) Installing isl26 (0.26-r1)
(11/43) Installing mpfr4 (4.2.0_p12-r0)
(12/43) Installing mpc1 (1.3.1-r1)
(13/43) Installing gcc (12.2.1_git20220924-r10)
(14/43) Installing libstdc++-dev (12.2.1_git20220924-r10)
(15/43) Installing musl-dev (1.2.4-r1)
(16/43) Installing libc-dev (0.7.2-r5)
(17/43) Installing g++ (12.2.1_git20220924-r10)
(18/43) Installing make (4.4.1-r1)
(19/43) Installing fortify-headers (1.1-r3)
(20/43) Installing patch (2.7.6-r10)
(21/43) Installing build-base (0.5-r3)
(22/43) Installing brotli-libs (1.0.9-r14)
(23/43) Installing libpng (1.6.39-r3)
(24/43) Installing freetype (2.13.0-r5)
(25/43) Installing brotli (1.0.9-r14)
(26/43) Installing pkgconf (1.9.5-r0)
(27/43) Installing brotli-dev (1.0.9-r14)
(28/43) Installing zlib-dev (1.2.13-r1)
(29/43) Installing libpng-dev (1.6.39-r3)
(30/43) Installing freetype-dev (2.13.0-r5)
(31/43) Installing libquadmath (12.2.1_git20220924-r10)
(32/43) Installing libgfortran (12.2.1_git20220924-r10)
(33/43) Installing gfortran (12.2.1_git20220924-r10)
(34/43) Installing linux-headers (6.3-r0)
(35/43) Installing openblas (0.3.23-r0)
(36/43) Installing liblapack (0.3.23-r0)
(37/43) Installing liblapacke (0.3.23-r0)
(38/43) Installing openblas-ilp64 (0.3.23-r0)
(39/43) Installing openblas-dev (0.3.23-r0)
(40/43) Installing libunistring (1.1-r1)
(41/43) Installing libidn2 (2.3.4-r1)
(42/43) Installing pcre2 (10.42-r1)
(43/43) Installing wget (1.21.4-r0)
Executing busybox-1.36.1-r2.trigger
OK: 378 MiB in 81 packages
Collecting spglib
  Downloading spglib-2.1.0.tar.gz (2.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 28.6 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting numpy (from spglib)
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/cd/fe/e900cb2ebafae04b7570081cefc65b6fdd9e202b9b353572506cea5cafdf/numpy-1.25.2-cp311-cp311-musllinux_1_1_x86_64.whl.metadata
  Downloading numpy-1.25.2-cp311-cp311-musllinux_1_1_x86_64.whl.metadata (5.6 kB)
Downloading numpy-1.25.2-cp311-cp311-musllinux_1_1_x86_64.whl (18.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.1/18.1 MB 117.4 MB/s eta 0:00:00
Building wheels for collected packages: spglib
  Building wheel for spglib (pyproject.toml): started
  Building wheel for spglib (pyproject.toml): finished with status 'done'
  Created wheel for spglib: filename=spglib-2.1.0-cp311-cp311-musllinux_1_2_x86_64.whl size=817926 sha256=69de5de9c1129f24e3dd746f51c92549063f42a2fa5bf0f0d1af8a09f83686b2
  Stored in directory: /tmp/pip-ephem-wheel-cache-2a60npcw/wheels/82/cb/9d/b2052daee0898d96ed957584615b5ae33213345ad7d056ec06
Successfully built spglib
Installing collected packages: numpy, spglib
Successfully installed numpy-1.25.2 spglib-2.1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
World updated, but the following packages are not removed due to:
  gcc: build-base gfortran openblas-dev

OK: 378 MiB in 81 packages
--> 3b3ad568305
STEP 7/9: COPY test.py ./
--> 2e594665337
STEP 8/9: WORKDIR /usr/src/app/data
--> 95463e784b2
STEP 9/9: CMD [ "../test.py" ]
COMMIT test/spglib
--> 42109c5121d
Successfully tagged localhost/test/spglib:latest
42109c5121d7d7993a2011d2ce22f18d36f257dfd665aed1fee64a7f383a47dc

# podman run --rm test/spglib
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/spglib/spglib.py", line 41, in <module>
    from spglib import _spglib as spg
ImportError: Error loading shared library libsymspg.so.2: No such file or directory (needed by /usr/local/lib/python3.11/site-packages/spglib/_spglib.cpython-311-x86_64-linux-musl.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/data/../test.py", line 2, in <module>
    import spglib
  File "/usr/local/lib/python3.11/site-packages/spglib/__init__.py", line 37, in <module>
    from .spglib import (  # noqa: F401
  File "/usr/local/lib/python3.11/site-packages/spglib/spglib.py", line 59, in <module>
    from spglib import _spglib as spg
ImportError: Error loading shared library libsymspg.so.2: No such file or directory (needed by /usr/local/lib/python3.11/site-packages/spglib/_spglib.cpython-311-x86_64-linux-musl.so)
#
```

It appears that this has to do with a change with how symspg is included by the library. In 2.0.2, there is no `libsymspg.so*` anywhere in the container (not even in `/usr/local/lib/python3.11/site-packages/spglib/`):
```
(container) # find / -iname 'libsymspg.so*'
(container) #
```
But the load succeeds because it appears symspg has been statically included in `_spglib.cpython-311-x86_64-linux-musl.so `. So `ldd` says everything is fine:
```
(container) # ldd _spglib.cpython-311-x86_64-linux-musl.so 
	/lib/ld-musl-x86_64.so.1 (0x7fa1adf86000)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7fa1adf86000)
	(then only the missing python functions, which go away when properly loaded by python)
```

However, in 2.1.0, symspg is no longer statically included, and instead it expects to load the symbols from another shared library, as reported by `ldd`:
```
(container) # ldd _spglib.cpython-311-x86_64-linux-musl.so 
	/lib/ld-musl-x86_64.so.1 (0x7fba3e97a000)
Error loading shared library libsymspg.so.2: No such file or directory (needed by _spglib.cpython-311-x86_64-linux-musl.so)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7fba3e97a000)
Error relocating _spglib.cpython-311-x86_64-linux-musl.so: spg_get_magnetic_spacegroup_type: symbol not found
Error relocating _spglib.cpython-311-x86_64-linux-musl.so: spg_get_spacegroup_type: symbol not found
Error relocating _spglib.cpython-311-x86_64-linux-musl.so: spgat_get_symmetry_with_collinear_spin: symbol not found
Error relocating _spglib.cpython-311-x86_64-linux-musl.so: spgat_standardize_cell: symbol not found
Error relocating _spglib.cpython-311-x86_64-linux-musl.so: spg_get_dense_grid_point_from_address: symbol not found
Error relocating _spglib.cpython-311-x86_64-linux-musl.so: spg_get_error_code: symbol not found
Error relocating _spglib.cpython-311-x86_64-linux-musl.so: spg_get_stabilized_reciprocal_mesh: symbol not found
Error relocating _spglib.cpython-311-x86_64-linux-musl.so: spg_get_dense_ir_reciprocal_mesh: symbol not found
... 
(also the missing python functions, which go away when properly loaded by python)
```

This is then what is failing. The problematic code is in `spglib.py`:
```
try:                                                                  
    from spglib import _spglib as spg                                 
except ImportError:                                                                  
    import os.path                                                                   
    import re                                                                        
    from ctypes import cdll                                                          
                                                                                     
    bundled_lib = next(                                                              
        filter(                                                                      
            lambda fl: re.match(".*symspg\\..*", fl),                                
            sorted(os.listdir(os.path.dirname(__file__))),                           
        ),                                                                           
        None,                                                                        
    )                                                                                
    if not bundled_lib:                                                              
        raise FileNotFoundError(                                                     
            "Spglib C++ library is not installed and no bundled version was detected"
        )                                                                            
    cdll.LoadLibrary(os.path.join(os.path.dirname(__file__), bundled_lib))           
    from spglib import _spglib as spg                                                
```

The `except` block is intended to allow loading of the bundled shared library when not found in the system `LD_LIBRARY_PATH`. However, this does not work as intended: while the `LoadLibrary` call does load `libsymspg` into python (replace that line with `print(cdll.LoadLibrary(os.path.join(os.path.dirname(__file__), bundled_lib)))` and the output is `<CDLL '/usr/local/lib/python3.11/site-packages/spglib/libsymspg.so', handle 7f770aae9450 at 0x7f772cb64290>`). its symbols are still not available for _spglib to use. 

This diagnosis is confirmed by creating a symlink from a normal library directory: `ln -s /usr/local/lib/python3.11/site-packages/spglib/libsymspg.so.2 /usr/local/lib/libsymspg.so.2` , after which SPGLIB import succeeds.

So the fix is to adjust the bundled library loading routine in `spglib.py` to properly add the bundled library location to the shared library search path. This is not completely trivial, since the loader has already read `LD_LIBRARY_PATH` by the time this python code is executed. Adjusting `_spglib.cpython-311-x86_64-linux-musl.so` so that the relevant rpath allows the loader to recognize that the cll.LoadLibrary library is the desired one, is one approach.

(Edited to confirm `libsymspg.so` of any version is not present on 2.0.2)

**Comment by LecrisUT** [comment]
Thanks for the Dockerfile that will help me test things.

> It appears that this has to do with a change with how symspg is included by the library. In 2.0.2, there is no `libsymspg.so.2` anywhere in the container (not even in `/usr/local/lib/python3.11/site-packages/spglib/`):

It was SOVERSION 1 at that point so `libsymspg.so.1`. But yeah, it used a static build there. The new version will use the system installed one and if not found, will default to bundled one.

> However, in 2.1.0, symspg is no longer statically included, and instead it expects to load the symbols from another shared library, as reported by `ldd`:

`readelf -d` would give better debug output for this issue.

> its symbols are still not available for _spglib to use.
> So the fix is to adjust the bundled library loading routine in `spglib.py` to properly add the bundled library location to the shared library search path.

:thinking: That is weird. Afaiu, if the symbols are loaded, and there are no hard-coded paths, it should use the already loaded symbols. I'll need to ask around about this one. If you have `LD_LIBRARY_PATH` set to `/usr/local/lib/python3.11/site-packages/spglib` it still does not behave properly?

**Comment by tmcqueen-materials** [comment]
If `LD_LIBRARY_PATH` is adjusted to include `/usr/local/lib/python3.11/site-packages/spglib` before invoking python, then it all works fine:
```
(container) # LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib/python3.11/site-packages/spglib" ../test.py
SPGLIB import succeeded.
```
But you cannot programmatically adjust `LD_LIBRARY_PATH` at runtime. Here is what `readelf -d` gives for 2.1.0 (for 2.0.2 obviously no libsymspg is listed):
```
# readelf -d _spglib.cpython-311-x86_64-linux-musl.so 

Dynamic section at offset 0x6c68 contains 24 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libsymspg.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libc.musl-x86_64.so.1]
 0x000000000000000c (INIT)               0x2000
 0x000000000000000d (FINI)               0x4be2
 0x0000000000000019 (INIT_ARRAY)         0x6c58
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x6c60
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x270
 0x0000000000000005 (STRTAB)             0x818
 0x0000000000000006 (SYMTAB)             0x2a8
 0x000000000000000a (STRSZ)              1423 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x6e38
 0x0000000000000002 (PLTRELSZ)           1128 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x1678
 0x0000000000000007 (RELA)               0xda8
 0x0000000000000008 (RELASZ)             2256 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x0000000000000018 (BIND_NOW)           
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x000000006ffffff9 (RELACOUNT)          87
 0x0000000000000000 (NULL)               0x0

```

**Comment by LecrisUT** [comment]
A quick patch solution is:
```console
$ patchelf --add-rpath /usr/local/lib/python3.11/site-packages/spglib /usr/local/lib/python3.11/site-packages/spglib/_spglib.cpython-311-x86_64-linux-musl.so
```

But we will need to get to the bottom of it and understand what's going on. I am reproducing the error in the docker environment and in the CI, so hopefully I can find a proper solution for this.

**Comment by tmcqueen-materials** [comment]
@LecrisUT : great. Yes, that quick patch works for me also. And yes, it would be great to find out why the loader isn't resolving the symbols with the ones loaded by loadlibrary and fix that (`patchelf --add-rpath "\$ORIGIN" /usr/local/lib/python3.11/site-packages/spglib/_spglib.cpython-311-x86_64-linux-musl.so` also works).

**Comment by LecrisUT** [comment]
I've posted it on pypa discord and on [python discuss](https://discuss.python.org/t/loading-dependency-of-python-binding-manually/33598) and [cpython](https://github.com/python/cpython/issues/109332).

The symbols themselves seem to be loaded correctly, but it's the `cdll.LoadLibrary`.  The only thing I can think of is if it has a different procedure of [`dlopen`](https://linux.die.net/man/3/dlopen) in the alpine version of cpython.

Note to self:
- Call ` ctypes.util.find_library("symspg")` instead of `try ... except`
- Could also do the library loading within `_spglib.c` and decouple `target_link_libraries`
  - Not sure if `dlopen` symbols are made available implicitly
  - Does it work on other OS?

**Comment by tmcqueen-materials** [comment]
@LecrisUT: Some potentially germane info here https://www.openwall.com/lists/musl/2022/01/12/2 . I confirm that this issue does not crop up on a python:slim (bookworm slim) variant and appears specific to musl . If you follow the thread above, it appears musl, by design, does not use already loaded symbols [in this case, those obtained by `LoadLibrary`] to avoid symbol confusion problems. The recommended solution in there is to make sure `rpath` or `runpath` is appropriately set (to, e.g., `\$ORIGIN`). I would recommend RUNPATH as I believe that then accomplishes your goal, and is fully cross-platform -- on load of `_spglib`, user specified library locations (`/etc/ld.so.conf` and `LD_LIBRARY_PATH`) will be checked before RUNPATH, so system `libsymspg` will take priority over the bundled one, if it exists.

[Edited to add summary of that thread and bugs documented therein].

**Comment by LecrisUT** [comment]
@tmcqueen-materials Do you know if this affects `pypy` or other python environments? This issue is popping up again on [conda](https://github.com/conda-forge/spglib-feedstock/pull/105#discussion_r1420874705) and I am trying to think again how to solve this issue.

My understanding of using `$ORIGIN` is to have it point to the `site-packages/spglib` folder so that the bundled library is picked up. But in that case, system installed package `/usr/lib64/libsysmspg.so` is not used, unless the user manually overwrites with `LD_LIBRARY_PATH` or equivalents. The priority that I would want is `LD_LIBRARY_PATH` -> `/usr/lib64` -> `site-packages/spglib`, but the last two are reversed if I use `rpath -> $ORIGIN`.

**Comment by LecrisUT** [comment]
@tmcqueen-materials Can you try it again with #520? I've removed the custom dynamic import there and baked in the RPATH.
